version: '3.3'

services:
  app:
    build: .
    container_name: c24-diploma-project
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/c24-diploma-project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    container_name: postgres_15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=c24-diploma-project
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: